### ISSUE TITLE
Failed to compile ...

### ISSUE THREAD

**Issue by bavariacoin** [zoldur/OmegaCore#1]
Ubuntu Server 16.04:
....
Cloning into 'sanchezium'...
remote: Counting objects: 916, done.
remote: Compressing objects: 100% (768/768), done.
remote: Total 916 (delta 133), reused 916 (delta 133), pack-reused 0
Receiving objects: 100% (916/916), 5.48 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (133/133), done.
Checking connectivity... done.
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/tmp/tmp.izeStZ0Ldw/sanchezium/src -I/tmp/tmp.izeStZ0Ldw/sanchezium/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/tmp/tmp.izeStZ0Ldw/sanchezium/src/secp256k1/include -I/tmp/tmp.izeStZ0Ldw/sanchezium/src/leveldb/include -I/tmp/tmp.izeStZ0Ldw/sanchezium/src/leveldb/helpers -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
make: g++: Command not found
makefile.unix:200: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 127
Failed to compile Sanchezium. Please investigate.
.....

**Comment by zoldur** [comment]
This is OmegaCore, not Sanchezium.
